version: '3.4'

services:
  krakenfiatpaymentstest:
    image: krakenfiatpaymentstest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fiat-import-worker
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - '6432:5432'
